[project]
name = "multi-agent-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "shashikant-bhardwaj", email = "bhardwajshashi531@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
multi-agent-system = "multi_agent_system:main"

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"
